# Generated by Django 3.1.6 on 2021-03-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonorDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=150)),
                ('bloodtype', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('password2', models.CharField(max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
