# Generated by Django 3.1.6 on 2021-03-19 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donordetail',
            name='password2',
        ),
    ]
