# Generated by Django 3.1.6 on 2021-03-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0002_remove_donordetail_password2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('username', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('donor_id', models.CharField(max_length=20)),
                ('telephone', models.CharField(max_length=20)),
                ('hospital', models.CharField(max_length=500)),
                ('hospital_location', models.CharField(max_length=750)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(max_length=100)),
                ('attended', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
