# Generated by Django 3.1.6 on 2021-03-24 18:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='next_appointment_due_date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
