# Generated by Django 3.1.6 on 2021-03-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0004_appointment_next_appointment_due_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(default='TQuXUK', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
