# Generated by Django 3.1.6 on 2021-03-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0005_auto_20210325_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='gBYXXF', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
