# Generated by Django 3.1.6 on 2021-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0006_auto_20210325_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='tkWsZc', max_length=50),
        ),
    ]
