# Generated by Django 3.1.6 on 2021-03-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0007_auto_20210325_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('answer_space_one', models.CharField(blank=True, max_length=1000)),
                ('answer_space_two', models.CharField(blank=True, max_length=1000)),
                ('show', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='cKTAdT', max_length=50),
        ),
    ]
