# Generated by Django 3.1.6 on 2021-03-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0008_auto_20210325_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='donordetail',
            name='address',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donordetail',
            name='city',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donordetail',
            name='country',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='SYBhZg', max_length=50),
        ),
    ]
