# Generated by Django 3.1.6 on 2021-03-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0009_auto_20210327_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='dVMTvz', max_length=50),
        ),
    ]
