# Generated by Django 3.1.6 on 2021-03-30 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0012_auto_20210330_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faq',
            old_name='show',
            new_name='show_on_dashboard',
        ),
        migrations.AddField(
            model_name='faq',
            name='show_on_home',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='yCDZxi', max_length=50),
        ),
    ]
