# Generated by Django 3.1.6 on 2021-04-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0017_auto_20210404_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=125)),
                ('has_donated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='uAMgue', max_length=50),
        ),
    ]
