# Generated by Django 3.1.6 on 2021-04-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0018_auto_20210404_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='CykftW', max_length=50),
        ),
    ]
