# Generated by Django 3.1.6 on 2021-04-09 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0027_auto_20210409_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='CZpNIp', max_length=50),
        ),
    ]
