# Generated by Django 3.1.6 on 2021-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0028_auto_20210409_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='arbOTw', max_length=50),
        ),
    ]
