# Generated by Django 3.1.6 on 2021-04-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0030_auto_20210409_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='oVWGZl', max_length=50),
        ),
    ]
