# Generated by Django 3.1.6 on 2021-04-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0031_auto_20210409_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='szwwCn', max_length=50),
        ),
    ]
