# Generated by Django 3.1.6 on 2021-04-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0033_auto_20210409_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='smZnLM', max_length=50),
        ),
    ]
