# Generated by Django 3.1.6 on 2021-04-09 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0040_auto_20210409_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='lUMNtK', max_length=50),
        ),
    ]
