# Generated by Django 3.1.6 on 2021-04-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0043_auto_20210409_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='fyTKMU', max_length=50),
        ),
    ]
