# Generated by Django 3.1.6 on 2021-04-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0048_auto_20210410_0533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='JMVkuX', max_length=50),
        ),
    ]
