# Generated by Django 3.1.6 on 2021-04-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0050_auto_20210410_0711'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('answer', models.CharField(blank=True, max_length=1000)),
                ('show_on_dashboard', models.BooleanField(default=True)),
                ('show_on_home', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='uDsObX', max_length=50),
        ),
    ]
