# Generated by Django 3.1.6 on 2021-04-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0053_auto_20210419_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='MbDFeY', max_length=50),
        ),
    ]
