# Generated by Django 3.1.6 on 2021-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0054_auto_20210419_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='EBKCrI', max_length=50),
        ),
    ]
