# Generated by Django 3.1.6 on 2021-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0055_auto_20210424_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='MarPgi', max_length=50),
        ),
    ]
