# Generated by Django 3.1.6 on 2021-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0056_auto_20210425_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='FIQHvM', max_length=50),
        ),
    ]
