# Generated by Django 3.1.6 on 2021-08-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0056_auto_20210807_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='FONRPR', max_length=50),
        ),
    ]
