# Generated by Django 3.1.6 on 2021-08-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0058_auto_20210812_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='HwEXqY', max_length=50),
        ),
    ]
