# Generated by Django 3.1.6 on 2021-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0062_auto_20210812_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='LSYKaX', max_length=50),
        ),
    ]
