# Generated by Django 3.1.6 on 2021-08-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donor', '0065_auto_20210812_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='d_id',
            field=models.CharField(default='jHFxMn', max_length=50),
        ),
    ]
