# Generated by Django 3.1.6 on 2021-04-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20210408_0344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='linkedin',
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='RlMwP', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='hBQtK', max_length=150),
        ),
    ]
