# Generated by Django 3.1.6 on 2021-04-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_auto_20210408_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author_picture',
            field=models.ImageField(upload_to='home/blog/author/image'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='vYJhs', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='YEnYb', max_length=150),
        ),
    ]
