# Generated by Django 3.1.6 on 2021-04-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210409_0815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='flickr',
            new_name='instagram',
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='ZupxK', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='YWMxS', max_length=150),
        ),
    ]
