# Generated by Django 3.1.6 on 2021-03-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountpath',
            name='color_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
