# Generated by Django 3.1.6 on 2021-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('expire', models.DateTimeField(blank=True)),
                ('pkz', models.CharField(max_length=64, unique=True)),
                ('sub_pk', models.CharField(max_length=10, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('sent', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='subadmin',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
