# Generated by Django 3.1.6 on 2021-03-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='home/slide')),
                ('title', models.CharField(max_length=63)),
                ('author', models.CharField(max_length=50)),
                ('author_picture', models.CharField(max_length=50)),
                ('author_bio', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=500)),
                ('message', models.CharField(max_length=2500)),
                ('start_time', models.CharField(max_length=10)),
                ('stop_time', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=150)),
                ('cost', models.CharField(max_length=20)),
                ('event_category', models.CharField(max_length=20)),
                ('social_url', models.CharField(max_length=250)),
                ('organizer', models.CharField(max_length=51)),
                ('organizer_phone', models.CharField(max_length=15)),
                ('organizer_email', models.CharField(max_length=65)),
                ('organizer_url', models.CharField(max_length=250)),
                ('venue', models.CharField(max_length=250)),
                ('venue_phone', models.CharField(max_length=15)),
                ('venue_email', models.CharField(max_length=250)),
                ('facebook', models.CharField(blank=True, max_length=250)),
                ('twitter', models.CharField(blank=True, max_length=250)),
                ('flickr', models.CharField(blank=True, max_length=250)),
                ('youtube', models.CharField(blank=True, max_length=250)),
                ('linkedin', models.CharField(blank=True, max_length=250)),
                ('donor', models.BooleanField(default=False)),
                ('recipient', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='home/slide')),
                ('name', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=10)),
                ('place_work', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=200)),
                ('donor', models.BooleanField(default=False)),
                ('recipient', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image/gallery')),
                ('name', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='HomeSlide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='home/slide')),
                ('sub_title', models.CharField(max_length=40)),
                ('line_one', models.CharField(max_length=20)),
                ('line_two', models.CharField(max_length=20)),
                ('line_three', models.CharField(max_length=20)),
                ('donor', models.BooleanField(default=False)),
                ('recipient', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='RequestAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=12)),
                ('time', models.CharField(max_length=12)),
                ('message', models.CharField(max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
