# Generated by Django 3.1.6 on 2021-03-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='image/blog')),
                ('title', models.CharField(max_length=35)),
                ('author', models.CharField(max_length=50)),
                ('author_picture', models.CharField(max_length=50)),
                ('author_bio', models.CharField(max_length=215)),
                ('tags', models.CharField(max_length=500)),
                ('category', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=150)),
                ('message', models.CharField(max_length=2500)),
                ('shrt_message', models.CharField(max_length=250)),
                ('facebook', models.CharField(blank=True, max_length=250)),
                ('twitter', models.CharField(blank=True, max_length=250)),
                ('flickr', models.CharField(blank=True, max_length=250)),
                ('youtube', models.CharField(blank=True, max_length=250)),
                ('linkedin', models.CharField(blank=True, max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='recipient',
        ),
    ]
