# Generated by Django 3.1.6 on 2021-03-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210317_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeslide',
            name='line_one',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='line_three',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='line_two',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='homeslide',
            name='sub_title',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
