# Generated by Django 3.1.6 on 2021-03-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210317_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
