# Generated by Django 3.1.6 on 2021-03-18 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210317_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='author_bio',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stop_time',
            field=models.DateTimeField(),
        ),
    ]
