# Generated by Django 3.1.6 on 2021-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210317_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='location',
            field=models.CharField(max_length=25),
        ),
    ]
