# Generated by Django 3.1.6 on 2021-03-18 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_campaign_shrt_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='picture',
            field=models.ImageField(upload_to='home/blog'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='stop_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='picture',
            field=models.ImageField(upload_to='home/feedback/picture'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='picture',
            field=models.ImageField(upload_to='home/gallery'),
        ),
    ]
