# Generated by Django 3.1.6 on 2021-04-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='show',
            field=models.BooleanField(default=False),
        ),
    ]
