# Generated by Django 3.1.6 on 2021-04-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210405_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='Q3LF3', max_length=150),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='NP1UA', max_length=150),
        ),
    ]
