# Generated by Django 3.1.6 on 2021-04-05 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210405_0159'),
    ]

    operations = [
        migrations.AddField(
            model_name='sayhello',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='cuzyY', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='HLMXv', max_length=150),
        ),
    ]
