# Generated by Django 3.1.6 on 2021-04-05 14:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20210405_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriber',
            name='expire',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='PUDmo', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='nfKeI', max_length=150),
        ),
    ]
