# Generated by Django 3.1.6 on 2021-04-09 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210409_1110'),
        ('home', '0019_auto_20210409_1106'),
    ]

    operations = [
    ]
