# Generated by Django 3.1.6 on 2021-04-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_auto_20210409_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='stFkq', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='bXRRZ', max_length=150),
        ),
    ]
