# Generated by Django 3.1.6 on 2021-04-09 23:20

from django.db import migrations, models
import django.db.models.deletion
import tagulous.models.fields
import tagulous.models.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20210409_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='flickr',
            new_name='instagram',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='campaign',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='event_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category'),
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='tags',
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='EvsiD', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='XcFJz', max_length=150),
        ),
        migrations.CreateModel(
            name='Tagulous_Campaign_tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('count', models.IntegerField(default=0, help_text='Internal counter of how many times this tag is in use')),
                ('protected', models.BooleanField(default=False, help_text='Will not be deleted when the count reaches 0')),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
                'unique_together': {('slug',)},
            },
            bases=(tagulous.models.models.BaseTagModel, models.Model),
        ),
        migrations.AddField(
            model_name='campaign',
            name='tags',
            field=tagulous.models.fields.TagField(_set_tag_meta=True, help_text='Enter a comma-separated tag string', to='home.Tagulous_Campaign_tags'),
        ),
    ]
