# Generated by Django 3.1.6 on 2021-04-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20210410_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeslide',
            name='show',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='csnjm', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='gVAjC', max_length=150),
        ),
    ]
