# Generated by Django 3.1.6 on 2021-08-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210424_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200, unique=True)),
                ('network', models.CharField(choices=[('Tron', 'Tron'), ('Binance', 'Binance'), ('Etherium', 'Etherium')], default=('Binance', 'Binance'), max_length=15)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='YTcdK', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='xxWgi', max_length=150),
        ),
    ]
