# Generated by Django 3.1.6 on 2021-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20210424_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='lng_id',
            field=models.CharField(default='DAJPTPBZFQYCEANFDPXSYYPDCIBCUJSSRKQNXEILNXPZQRFPRRZZIKUNNFPNWESB', max_length=70),
        ),
        migrations.AddField(
            model_name='blog',
            name='shrt_id',
            field=models.CharField(default='LBEWYVWZ', max_length=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='ZrNVV', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='IlYfa', max_length=150),
        ),
    ]
