# Generated by Django 3.1.6 on 2021-04-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_auto_20210425_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='lng_id',
            field=models.CharField(default='sygpuNoJqBFnbDFxyAgAcCxNdSlFZeggkFudMXwycMgllNFoptRonypLlaDSCqeW', max_length=70),
        ),
        migrations.AlterField(
            model_name='blog',
            name='shrt_id',
            field=models.CharField(default='BKRCBUYD', max_length=10),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='rymAk', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='LDEiU', max_length=150),
        ),
    ]
