# Generated by Django 3.1.6 on 2021-08-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_auto_20210811_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=30)),
                ('account_holder', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='SJfEJ', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='NRigJ', max_length=150),
        ),
    ]
