# Generated by Django 3.1.6 on 2021-08-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20210812_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaccount',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='rIENE', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='vstfn', max_length=150),
        ),
    ]
