# Generated by Django 3.1.6 on 2021-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20210812_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaccount',
            name='network',
            field=models.CharField(choices=[('BSC: Binance Smart Chain (BEP20)', 'BSC: Binance Smart Chain (BEP20)'), ('Ethereum (ERC20', 'Ethereum (ERC20)')], default=('Ethereum (ERC20', 'Ethereum (ERC20)'), max_length=300),
        ),
        migrations.AlterField(
            model_name='partner',
            name='class_id',
            field=models.CharField(default='aSnro', max_length=150),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='class_id',
            field=models.CharField(default='rElLm', max_length=150),
        ),
    ]
