# Generated by Django 3.1.6 on 2021-04-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='tell_us',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='what',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='where',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='why',
            field=models.CharField(max_length=500),
        ),
    ]
