# Generated by Django 3.1.6 on 2021-03-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=12)),
                ('mail', models.BooleanField(default=True)),
                ('answer_one', models.CharField(max_length=500)),
                ('answer_two', models.CharField(max_length=20)),
                ('answer_three', models.CharField(max_length=20)),
                ('answer_four', models.CharField(max_length=20)),
                ('answer_five', models.CharField(max_length=20)),
                ('answer_six', models.CharField(max_length=20)),
                ('answer_seven', models.CharField(max_length=500)),
                ('answer_eight', models.CharField(max_length=20)),
                ('answer_nine', models.CharField(max_length=500)),
                ('answer_ten', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
